repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: detect-private-key
    -   id: detect-aws-credentials
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
    -   id: gitleaks
